server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: trace
#    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          messaging-client-oidc:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: messaging-client-oidc
          messaging-client-device-grant:
            provider: spring-device
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: urn:ietf:params:oauth:grant-type:device_code
            scope: message.read,message.write
            client-name: messaging-client-device-grant
        provider:
          spring:
            issuer-uri: http://localhost:9000
          spring-device:
            issuer-uri: http://localhost:9000
            authorization-uri: http://localhost:9000/oauth2/device/device_authorization
            token-uri: http://localhost:9000/oauth2/device/token

messages:
  base-uri: http://127.0.0.1:8090/messages
