server:
  port: 9000

spring:
  thymeleaf:
    cache: false
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

logging:
  level:
    org.springframework.security: trace